Signup
RobertoCarrilloAvila/target pull request #4
Opened 2022-11-22 23:52 UTC by RobertoCarrilloAvila

2022-11-25 21:09 UTC, marcos09 requested changes
Great job, in general it looks good to me but I leave a couple of comments. 

Another thing you could try to add is internationalization (Maybe in other PR later) It's not mandatory for this project but always it's useful to have it because you don't know when your project could be needed in other languages

2022-11-25 21:09 UTC, marcos09 commented on src/components/SignUp/SignUp.js
> +  const [redirect, setRedirect] = useState(false);
I recommend you use a form validation library like Zod Validations or React hook form instead of these states.

2022-11-30 18:19 UTC, RobertoCarrilloAvila commented on src/components/SignUp/SignUp.js
> +  };
Done!

2022-11-30 18:20 UTC, RobertoCarrilloAvila commented on src/components/SignUp/SignUp.js
> +  const [redirect, setRedirect] = useState(false);
I'm going to implement the library in the next PR

2022-11-30 18:32 UTC, marcos09 requested changes
You could make it easy only sending setState in onChange prop

2022-11-30 18:32 UTC, marcos09 commented on src/components/SignUp/SignUp.js
> +              onChange={(value) => setName(value)}
You could make it easy only sending setName in onChange prop
```suggestion
              onChange={setName}
```

2022-11-30 18:32 UTC, marcos09 commented on src/components/SignUp/SignUp.js
> +              onChange={(value) => setEmail(value)}
You could make it easy only sending setName in onChange prop

```suggestion
              onChange={setEmail}
```

2022-11-30 18:32 UTC, marcos09 commented on src/components/SignUp/SignUp.js
> +              onChange={(value) => setPassword(value)}
```suggestion
              onChange={setPassword}
```

2022-11-30 18:32 UTC, marcos09 commented on src/components/SignUp/SignUp.js
> +              onChange={(value) => setPasswordConfirmation(value)}
```suggestion
              onChange={setPasswordConfirmation}
```

2022-11-30 18:32 UTC, marcos09 commented on src/components/SignUp/SignUp.js
> +              onChange={(value) => setGender(value)}
```suggestion
              onChange={setGender}
```

2022-11-30 18:40 UTC, RobertoCarrilloAvila commented on src/components/SignUp/SignUp.js
> +              onChange={(value) => setGender(value)}
Done!

2022-11-30 18:41 UTC, marcos09 approved these changes

2022-11-30 18:42 UTC, merged